=== ta11dave/Beer-App-V6/data/fermentables.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="fermentables" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="fermentables">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="GUID" type="9" value="I534RNkL3UW28A7iy+Arig==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAjnfhE2QvdRbbwDuLL4CuKAAAAAIL2rir3eOVAAAAAAAAAAABmAGUA
cgBtAGUAbgB0AGEAYgBsAGUAcwAAAAAAAAAc9PAI0DVgT5DHn0EvIso9BwAAACOd
+ETZC91FtvAO4svgK4pHAHIAYQBpAG4AAAAAAAAAKqhlQDgemEKi7uoY6O33xAcA
AAAjnfhE2QvdRbbwDuLL4CuKTwByAGkAZwBpAG4AAAAAAAAAOouF/hzw60C3f+Qh
dVp7qwcAAAAjnfhE2QvdRbbwDuLL4CuKQwBvAGwAbwByAAAAAAAAAPGfVrs1krZA
jr6OKi538+EHAAAAI534RNkL3UW28A7iy+Arik0AYQBzAGgAPwAAAAAAAACk1YD6
u9qyRbbsMFp0D/oLBwAAACOd+ETZC91FtvAO4svgK4pQAG8AdABlAG4AdABpAGEA
bAAAAAAAAAAfnA/EQMgzQoc5JSTU1fXrBwAAACOd+ETZC91FtvAO4svgK4pNAGEA
eACgACUAAAAAAAAAPMPxsT91eUS3SOaH3/UKTQcAAAAjnfhE2QvdRbbwDuLL4CuK
TgBvAHQAZQBzAAAAAAAAAFf7I/BBg91Bshrz7V9/J0EHAAAAI534RNkL3UW28A7i
y+ArilAAbwB3AGUAcgAAAAAAAABti/bqmSpYQ7bjnCa4Jg9sBwAAACOd+ETZC91F
tvAO4svgK4pQAEgAAAAAAAAA5YnhipZ5l0upLW3mMR69CwcAAAAjnfhE2QvdRbbw
DuLL4CuKRgAxADAAAAAAAAAAcReeHGQbLEay3OqtTD6qwAcAAAAjnfhE2QvdRbbw
DuLL4CuKRgAxADEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwAAAAFAAAAAAAAAAAA
AAAAAAAAAAA=
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Grain" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="HPTwCNA1YE+Qx59BLyLKPQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Origin" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="KqhlQDgemEKi7uoY6O33xA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Color" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="GUID" type="9" value="OouF/hzw60C3f+QhdVp7qw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Mash_x003F_" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="8Z9WuzWStkCOvo4qLnfz4Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Potential" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="GUID" type="9" value="pNWA+rvaskW27DBadA/6Cw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Max_x00A0__x0025_" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="GUID" type="9" value="H5wPxEDIM0KHOSUk1NX16w==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Notes" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="PMPxsT91eUS3SOaH3/UKTQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Power" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="GUID" type="9" value="V/sj8EGD3UGyGvPtX38nQQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="PH" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="GUID" type="9" value="bYv26pkqWEO245wmuCYPbA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Field10" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="5YnhipZ5l0upLW3mMR69Cw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Field11" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="cReeHGQbLEay3OqtTD6qwA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== ta11dave/Beer-App-V6/data/fermentables.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="fermentables.xsd" generated="2020-05-24T17:36:11">
<fermentables>
<Grain>Apple Juice</Grain>
<Origin>N/A</Origin>
<Color>5</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.05</Potential>
<Max_x00A0__x0025_>1</Max_x00A0__x0025_>
<Notes>Juice. Really it&apos;s hard cider if you&apos;re using 100%. </Notes>
<Power>0</Power>
<PH>3.675</PH>
</fermentables>
<fermentables>
<Grain>Amber Malt</Grain>
<Origin>United Kingdom</Origin>
<Color>22</Color>
<Mash_x003F_>X</Mash_x003F_>
<Potential>1.035</Potential>
<Max_x00A0__x0025_>0.2</Max_x00A0__x0025_>
<Notes>Roasted specialty malt used in some English browns, milds and old ales to add color and a biscuit taste. Intense flavor - so limit use. Low diastatic power so must be mashed with well modified malts.</Notes>
<Power>20</Power>
<PH>5.5</PH>
</fermentables>
<fermentables>
<Grain>Aromatic Malt</Grain>
<Origin>Belgium</Origin>
<Color>26</Color>
<Mash_x003F_>X</Mash_x003F_>
<Potential>1.036</Potential>
<Max_x00A0__x0025_>0.1</Max_x00A0__x0025_>
<Notes>Provides a very strong malt flavor and aroma to your beer.</Notes>
<Power>29</Power>
<PH>5.7</PH>
</fermentables>
<fermentables>
<Grain>Barley, Flaked</Grain>
<Origin>US</Origin>
<Color>1.7</Color>
<Mash_x003F_>X</Mash_x003F_>
<Potential>1.032</Potential>
<Max_x00A0__x0025_>0.2</Max_x00A0__x0025_>
<Notes>Adds significant body to Porters and Stouts. High haze producing protein prevents use in light beers.</Notes>
<Power>0</Power>
<PH>5.7</PH>
</fermentables>
<fermentables>
<Grain>Barley, Raw</Grain>
<Origin>US</Origin>
<Color>2</Color>
<Mash_x003F_>X</Mash_x003F_>
<Potential>1.028</Potential>
<Max_x00A0__x0025_>0.15</Max_x00A0__x0025_>
<Notes>Raw, unmalted barley can be used to add body to your beer. Use in homebrew requires very fine milling combined with a decoction or multi-stage mash. Performs best when used in small quantities with well modified grains.</Notes>
<Power>0</Power>
<PH>5.7</PH>
</fermentables>
<fermentables>
<Grain>Barley, Roasted</Grain>
<Origin>US</Origin>
<Color>300</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.025</Potential>
<Max_x00A0__x0025_>0.1</Max_x00A0__x0025_>
<Notes>Roasted at high temperature to create a burnt, grainy, coffee like flavor. Imparts a red to deep brown color to beer, and very strong roasted flavor. Use 2-4% in Brown ales to add a nutty flavor, or 3-10% in Porters and Stouts for coffee flavor.</Notes>
<Power>0</Power>
<PH>4.71</PH>
</fermentables>
<fermentables>
<Grain>Barley, Torrefied</Grain>
<Origin>US</Origin>
<Color>1.7</Color>
<Mash_x003F_>X</Mash_x003F_>
<Potential>1.036</Potential>
<Max_x00A0__x0025_>0.4</Max_x00A0__x0025_>
<Notes>Raw barley that has been &quot;popped&quot; open to open kernels Used in place of raw barley for faster conversion and higher yields. High in haze producing protein</Notes>
<Power>0</Power>
<PH>5.7</PH>
</fermentables>
<fermentables>
<Grain>Belgian Debittered Black Malt</Grain>
<Origin>Belgian</Origin>
<Color>550</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.01</Potential>
<Max_x00A0__x0025_>0.1</Max_x00A0__x0025_>
<Notes>-</Notes>
<Power>0</Power>
<PH>4.71</PH>
</fermentables>
<fermentables>
<Grain>Biscuit Malt</Grain>
<Origin>United Kingdom</Origin>
<Color>23</Color>
<Mash_x003F_>X</Mash_x003F_>
<Potential>1.036</Potential>
<Max_x00A0__x0025_>0.1</Max_x00A0__x0025_>
<Notes>Use for English ales, brown ales and porters. Adds a biscuit like flavor and aroma. Can be used as a substitute for toasted malt.</Notes>
<Power>6</Power>
<PH>5.7</PH>
</fermentables>
<fermentables>
<Grain>Black (Patent) Malt</Grain>
<Origin>US</Origin>
<Color>500</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.025</Potential>
<Max_x00A0__x0025_>0.1</Max_x00A0__x0025_>
<Notes>Dark color and dry roasted flavor characteristic of Stouts and Porters Use for: Coloring in small amounts, or flavoring of Stouts and Porters in larger amounts.</Notes>
<Power>0</Power>
<PH>4.71</PH>
</fermentables>
<fermentables>
<Grain>Black Barley (Briess)</Grain>
<Origin>US</Origin>
<Color>500</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.032</Potential>
<Max_x00A0__x0025_>1</Max_x00A0__x0025_>
<Notes>-</Notes>
<Power>0</Power>
<PH>4.71</PH>
</fermentables>
<fermentables>
<Grain>Black Barley (Stout)</Grain>
<Origin>US</Origin>
<Color>500</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.025</Potential>
<Max_x00A0__x0025_>0.1</Max_x00A0__x0025_>
<Notes>Unmalted barley roasted at high temperature to create a dry, coffee like flavor. Imparts a sharp acrid flavor characteristic of dry stouts. Gives &quot;dryness&quot; to a stout or porter -- much more so than regular Roasted Barley</Notes>
<Power>0</Power>
<PH>4.71</PH>
</fermentables>
<fermentables>
<Grain>Blackprinz Malt</Grain>
<Origin>US</Origin>
<Color>500</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.025</Potential>
<Max_x00A0__x0025_>0.1</Max_x00A0__x0025_>
<Notes>Dark color and dry roasted flavor characteristic of Stouts and Porters Use for: Coloring in small amounts, or flavoring of Stouts and Porters in larger amounts.</Notes>
<Power>0</Power>
<PH>4.71</PH>
</fermentables>
<fermentables>
<Grain>Blackprinz Malt (Briess)</Grain>
<Origin>US</Origin>
<Color>500</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.033</Potential>
<Max_x00A0__x0025_>0.1</Max_x00A0__x0025_>
<Notes>Dehusked Black Malt, similar to Weyermann CARAFA® Special. Very delicate roasted flavors. No astrigent or bitter aftertaste. Color: 500 L</Notes>
<Power>0</Power>
<PH>4.71</PH>
</fermentables>
<fermentables>
<Grain>Brewers Malt 6-Row (Briess)</Grain>
<Origin>US</Origin>
<Color>1.8</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.036</Potential>
<Max_x00A0__x0025_>1</Max_x00A0__x0025_>
<Notes>Flavor:Mild Grainy Malty More husk than 2-row, well suited for high adjunct brewing</Notes>
<Power>160</Power>
<PH>5.7</PH>
</fermentables>
<fermentables>
<Grain>Brown Malt</Grain>
<Origin>United Kingdom</Origin>
<Color>65</Color>
<Mash_x003F_>X</Mash_x003F_>
<Potential>1.032</Potential>
<Max_x00A0__x0025_>0.1</Max_x00A0__x0025_>
<Notes>Imparts a dry, biscuit flavor. Used in nut brown ales, porters and some Belgian ales.</Notes>
<Power>0</Power>
<PH>5.7</PH>
</fermentables>
<fermentables>
<Grain>Brown Sugar, Light</Grain>
<Origin>-</Origin>
<Color>10</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.035</Potential>
<Max_x00A0__x0025_>0.1</Max_x00A0__x0025_>
<Notes>Sugar. Caramel notes.</Notes>
<Power>0</Power>
<PH>5.7</PH>
</fermentables>
<fermentables>
<Grain>Brown Sugar, Dark</Grain>
<Origin>-</Origin>
<Color>20</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.035</Potential>
<Max_x00A0__x0025_>0.1</Max_x00A0__x0025_>
<Notes>Sugar. Caramel notes. More intense than other sugars</Notes>
<Power>0</Power>
<PH>5.7</PH>
</fermentables>
<fermentables>
<Grain>Brumalt</Grain>
<Origin>Germany</Origin>
<Color>23</Color>
<Mash_x003F_>X</Mash_x003F_>
<Potential>1.033</Potential>
<Max_x00A0__x0025_>0.1</Max_x00A0__x0025_>
<Notes>Dark German malt developed to add malt flavor of Alt, Marzen and Oktoberfest beers. Helps create authentic maltiness without having to do a decoction mash. Rarely available for homebrewers.</Notes>
<Power>0</Power>
<PH>5.7</PH>
</fermentables>
<fermentables>
<Grain>Cara-Pils/Dextrine</Grain>
<Origin>US</Origin>
<Color>2</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.033</Potential>
<Max_x00A0__x0025_>0.2</Max_x00A0__x0025_>
<Notes>Significantly increases foam/head retention and body of the beer. Also sold under the names &quot;Dextrine&quot; and &quot;Cara-Foam&quot;</Notes>
<Power>0</Power>
<PH>5.7</PH>
</fermentables>
<fermentables>
<Grain>Caraamber</Grain>
<Origin>US</Origin>
<Color>30</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.035</Potential>
<Max_x00A0__x0025_>0.2</Max_x00A0__x0025_>
<Notes>Adds body, color and improves head retention. Also called &quot;Crystal&quot; malt.</Notes>
<Power>0</Power>
<PH>5.7</PH>
</fermentables>
<fermentables>
<Grain>Caraaroma</Grain>
<Origin>Germany</Origin>
<Color>130</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.035</Potential>
<Max_x00A0__x0025_>0.15</Max_x00A0__x0025_>
<Notes>Very dark crystal malt - similar to a crystal 120 or Caramunich 120 malt. Adds strong caramel flavor, red color, and malty aroma.</Notes>
<Power>0</Power>
<PH>4.71</PH>
</fermentables>
<fermentables>
<Grain>Carafa I</Grain>
<Origin>Germany</Origin>
<Color>337</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.032</Potential>
<Max_x00A0__x0025_>0.05</Max_x00A0__x0025_>
<Notes>Used to intensify aroma and color in dark, Munich beers and stouts.</Notes>
<Power>0</Power>
<PH>4.71</PH>
</fermentables>
<fermentables>
<Grain>Carafa I (Weyermann)</Grain>
<Origin>Germany</Origin>
<Color>320</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.036</Potential>
<Max_x00A0__x0025_>0.05</Max_x00A0__x0025_>
<Notes>Chocolate malt. Dark beers, Alts, Bockbiers. Adds color and aroma. </Notes>
<Power>0</Power>
<PH>4.71</PH>
</fermentables>
<fermentables>
<Grain>Carafa II</Grain>
<Origin>Germany</Origin>
<Color>412</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.032</Potential>
<Max_x00A0__x0025_>0.05</Max_x00A0__x0025_>
<Notes>Used to intensify aroma and color in dark, Munich beers and stouts.</Notes>
<Power>0</Power>
<PH>4.71</PH>
</fermentables>
<fermentables>
<Grain>Carafa III</Grain>
<Origin>Germany</Origin>
<Color>525</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.032</Potential>
<Max_x00A0__x0025_>0.05</Max_x00A0__x0025_>
<Notes>Dark color and aroma - used in some German beers</Notes>
<Power>0</Power>
<PH>4.71</PH>
</fermentables>
<fermentables>
<Grain>Carafa Special I (Weyermann)</Grain>
<Origin>Germany</Origin>
<Color>320</Color>
<Mash_x003F_>-</Mash_x003F_>
<Potential>1.036</Potential>
<Max_x00A0__x0025_>0.05</Max_x00A0__x0025_>
<Notes>Chocolate malt. Dark beers, Alts, Bockbiers. Adds color and aroma. De-husked, smoother tasting</Notes>
<Power>0</Power>
