=== ta11dave/Beer-App-V6/data/Water.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="Water" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="Water">
<xsd:annotation>
<xsd:appinfo>
<od:tableProperty name="GUID" type="9" value="j/Pp83HQE0qsf8gYS8i7vQ==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAACP8+nzcdATSqx/yBhLyLu9AAAAAPgTbU/3eOVAAAAAAAAAAABXAGEA
dABlAHIAAAAAAAAALcH0KI1MB0C6aw+0OWFoEQcAAACP8+nzcdATSqx/yBhLyLu9
TgBhAG0AZQAAAAAAAACOEA47/6/LTZRqPMxVsrEGBwAAAI/z6fNx0BNKrH/IGEvI
u71DAGEAbABjAGkAdQBtAAAAAAAAACTqOVwqk/VKtXwlbZpT7zYHAAAAj/Pp83HQ
E0qsf8gYS8i7vU0AYQBnAG4AZQBzAGkAdQBtAAAAAAAAAJczZvJTWDNHkzId4Prq
XG0HAAAAj/Pp83HQE0qsf8gYS8i7vVMAdQBsAGYAYQB0AGUAAAAAAAAAEWBM/uT3
LUqlr+fJ17gA0AcAAACP8+nzcdATSqx/yBhLyLu9UwBvAGQAaQB1AG0AAAAAAAAA
17OH7Pzg40WlEwBt/Cae+AcAAACP8+nzcdATSqx/yBhLyLu9QwBoAGwAbwByAGkA
ZABlAAAAAAAAAKvtP8O2BVpDuf65L9M7kd4HAAAAj/Pp83HQE0qsf8gYS8i7vUIA
aQBjAGEAcgBiAG8AbgBhAHQAZQAAAAAAAAAHV/ercwOvSbhgnJJNtGjZBwAAAI/z
6fNx0BNKrH/IGEvIu71GAGkAZQBsAGQAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
DAAAAAUAAAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Name" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="LcH0KI1MB0C6aw+0OWFoEQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Calcium" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="GUID" type="9" value="jhAOO/+vy02UajzMVbKxBg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Magnesium" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="GUID" type="9" value="JOo5XCqT9Uq1fCVtmlPvNg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Sulfate" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="GUID" type="9" value="lzNm8lNYM0eTMh3g+upcbQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Sodium" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="GUID" type="9" value="EWBM/uT3LUqlr+fJ17gA0A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Chloride" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="GUID" type="9" value="17OH7Pzg40WlEwBt/Cae+A==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Bicarbonate" minOccurs="0" od:jetType="double" od:sqlSType="float" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="General Number"/>
<od:fieldProperty name="GUID" type="9" value="q+0/w7YFWkO5/rkv0zuR3g==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="Field8" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="Format" type="10" value="@"/>
<od:fieldProperty name="GUID" type="9" value="B1f3q3MDr0m4YJySTbRo2Q==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== ta11dave/Beer-App-V6/data/Water.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="Water.xsd" generated="2020-05-24T17:36:46">
<Water>
<Name>Balanced</Name>
<Calcium>80</Calcium>
<Magnesium>5</Magnesium>
<Sulfate>80</Sulfate>
<Sodium>25</Sodium>
<Chloride>75</Chloride>
<Bicarbonate>100</Bicarbonate>
</Water>
<Water>
<Name>Balanced II</Name>
<Calcium>150</Calcium>
<Magnesium>10</Magnesium>
<Sulfate>160</Sulfate>
<Sodium>80</Sodium>
<Chloride>150</Chloride>
<Bicarbonate>220</Bicarbonate>
</Water>
<Water>
<Name>Burton</Name>
<Calcium>275</Calcium>
<Magnesium>40</Magnesium>
<Sulfate>610</Sulfate>
<Sodium>25</Sodium>
<Chloride>35</Chloride>
<Bicarbonate>270</Bicarbonate>
</Water>
<Water>
<Name>Dusseldorf (Altbier)</Name>
<Calcium>90</Calcium>
<Magnesium>12</Magnesium>
<Sulfate>45</Sulfate>
<Sodium>82</Sodium>
<Chloride>65</Chloride>
<Bicarbonate>223</Bicarbonate>
</Water>
<Water>
<Name>Dortmund</Name>
<Calcium>230</Calcium>
<Magnesium>15</Magnesium>
<Sulfate>330</Sulfate>
<Sodium>40</Sodium>
<Chloride>130</Chloride>
<Bicarbonate>235</Bicarbonate>
</Water>
<Water>
<Name>Dublin (Dry Stout)</Name>
<Calcium>120</Calcium>
<Magnesium>4</Magnesium>
<Sulfate>55</Sulfate>
<Sodium>12</Sodium>
<Chloride>19</Chloride>
<Bicarbonate>315</Bicarbonate>
</Water>
<Water>
<Name>Edinburgh (Scottish/Malty Ale)</Name>
<Calcium>100</Calcium>
<Magnesium>20</Magnesium>
<Sulfate>140</Sulfate>
<Sodium>55</Sodium>
<Chloride>50</Chloride>
<Bicarbonate>285</Bicarbonate>
</Water>
<Water>
<Name>Malty Balanced</Name>
<Calcium>90</Calcium>
<Magnesium>5</Magnesium>
<Sulfate>60</Sulfate>
<Sodium>25</Sodium>
<Chloride>95</Chloride>
<Bicarbonate>100</Bicarbonate>
</Water>
<Water>
<Name>London (Porter)</Name>
<Calcium>70</Calcium>
<Magnesium>6</Magnesium>
<Sulfate>40</Sulfate>
<Sodium>15</Sodium>
<Chloride>38</Chloride>
<Bicarbonate>166</Bicarbonate>
</Water>
<Water>
<Name>Munich (Dark Lager)</Name>
<Calcium>77</Calcium>
<Magnesium>17</Magnesium>
<Sulfate>18</Sulfate>
<Sodium>4</Sodium>
<Chloride>8</Chloride>
<Bicarbonate>295</Bicarbonate>
</Water>
<Water>
<Name>Pilsen (Light Lager)</Name>
<Calcium>7</Calcium>
<Magnesium>2</Magnesium>
<Sulfate>8</Sulfate>
<Sodium>2</Sodium>
<Chloride>6</Chloride>
<Bicarbonate>16</Bicarbonate>
</Water>
<Water>
<Name>Vienna</Name>
<Calcium>75</Calcium>
<Magnesium>15</Magnesium>
<Sulfate>60</Sulfate>
<Sodium>10</Sodium>
<Chloride>15</Chloride>
<Bicarbonate>225</Bicarbonate>
</Water>
<Water>
<Name>Light &amp; Hoppy</Name>
<Calcium>75</Calcium>
<Magnesium>5</Magnesium>
<Sulfate>150</Sulfate>
<Sodium>10</Sodium>
<Chloride>50</Chloride>
<Bicarbonate>0</Bicarbonate>
</Water>
<Water>
<Name>Light &amp; Malty</Name>
<Calcium>60</Calcium>
<Magnesium>5</Magnesium>
<Sulfate>55</Sulfate>
<Sodium>10</Sodium>
<Chloride>95</Chloride>
<Bicarbonate>0</Bicarbonate>
</Water>
</dataroot>
